SELECT 
    a.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY,
    SUM(bs.SALES * b.PRICE) as TOTAL_SALES
FROM AUTHOR a
JOIN BOOK b ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
WHERE YEAR(bs.SALES_DATE) = 2022 
AND MONTH(bs.SALES_DATE) = 1
GROUP BY a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY a.AUTHOR_ID ASC, b.CATEGORY DESC;