SELECT 
    YEAR(sales.SALES_DATE) as YEAR,
    MONTH(sales.SALES_DATE) as MONTH,
    users.GENDER,
    COUNT(DISTINCT sales.USER_ID) as USERS
FROM ONLINE_SALE sales
JOIN USER_INFO users ON sales.USER_ID = users.USER_ID
WHERE users.GENDER IS NOT NULL
GROUP BY 
    YEAR(sales.SALES_DATE),
    MONTH(sales.SALES_DATE),
    users.GENDER
ORDER BY YEAR, MONTH, GENDER;