SELECT 
    FP.PRODUCT_ID, 
    FP.PRODUCT_NAME, 
    SUM(FO.AMOUNT * FP.PRICE) as TOTAL_SALES
FROM FOOD_PRODUCT FP 
JOIN FOOD_ORDER FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
group by PRODUCT_ID
ORDER BY 3 DESC, 1 ASC;